version: "3.7"
services:
  eit-web-ar:
    image: node:12
    container_name: eit-web-ar-development_container
    tty: true # Keep container running. This option is not available if you build from a dockerfile.
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node-modules
        target: /app/node_modules
    ports:
      - "3000:3000"
    links:
      - redis:redis

  redis:
    image: "redis:alpine"
    
  api:
    image: node:12
    container_name: eit-web-ar-development_api
    tty: true
    working_dir: /api
    volumes:
      - type: bind
        source: ./src/api
        target: /api
      - type: volume
        source: node-modules
        target: /api/node_modules
    ports:
      - "3001:3001"

volumes:
  node-modules:
    name: eit-web-ar_node-modules