version: "3.7"
services:
  frontend:
    image: node:12
    container_name: eit-web-ar-development_frontend
    tty: true # Keep container running. This option is not available if you build from a dockerfile.
    working_dir: /frontend
    volumes:
      - type: bind
        source: ./src/frontend
        target: /frontend
      - type: volume
        source: frontend-node-modules
        target: /frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      - frontend

  redis:
    image: "redis:alpine"
    networks:
      - backend

  api:
    image: node:12
    container_name: eit-web-ar-development_api
    tty: true
    working_dir: /api
    volumes:
      - type: bind
        source: ./src/api
        target: /api
      - type: volume
        source: api-node-modules
        target: /api/node_modules
    ports:
      - "3001:3001"
    networks:
      - frontend
      - backend

volumes:
  frontend-node-modules:
    name: eit-web-ar_frontend-node-modules
  api-node-modules:
    name: eit-web-ar_api-node-modules

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge